name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.11.2
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run tests
        run: |
          for file in *.py; do
            python3 "$file"
          done
